version: '3.1'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.5.7'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.4.0'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Allow external listeners (running outside of docker) to reach kafka on localhost:29092
      # see https://github.com/bitnami/bitnami-docker-kafka#accessing-kafka-with-internal-and-external-clients
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:3.8.16-alpine
    ports:
      - 5672:5672    # AMQP
      - 15672:15672  # Web UI

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
